site_name: Unreal SDK
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/beamable-badge.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: blue

repo_url: https://github.com/Beamable/UnrealSDK
repo_name: Beamable/UnrealSDK

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

plugins:
   - glightbox

nav:  
  - Use Guide: 
    - Intro: 'Use Guide/Unreal SDK - Intro.md'
    - Content: 'Use Guide/Unreal SDK - Content.md'
  - SDK Development Guide: 'SDK Development Guide/OAPI Code Gen.md'

copyright: |
  &copy; 2024 <a href="https://github.com/Beamable"  target="_blank" rel="noopener">Beamable</a>