name: Linux Server Build - Template

on:  
  workflow_call:
    inputs:
      beamProj:
        description: 'The BEAMPROJ we are building. Ie: BEAMPROJ_Sandbox or BEAMPROJ_HathoraDemo.'
        required: true
        default: 'BEAMPROJ_Sandbox'
        type: string

permissions:
  contents: write

jobs:
  deploy:
    runs-on: unreal-builder
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Prepare Repository for compilation
        run: bash init_repo.sh
      - name: Set BeamProjOverride.txt
        run: |
          echo ${{ inputs.beamProj }} > BeamProjOverride.txt |
          cat BeamProjOverride.txt
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Pull base image
        run: bash docker_build.sh server
      - name: Compress Directory
        run: tar cvzf linux_server.tar.gz PackagedProject/LinuxServer
      - name: Upload Compressed Folder as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux Server build
          path: linux_server.tar.gz