name: Build - Windows - Client - Dev

on:
  workflow_dispatch:
    inputs:
      buildAll:
        type: boolean
        description: 'Whether or not we should build all BEAMPROJS instead of just the ones with changes.'
        required: true
        default: false      
  push:
    branches:
      - dev    
  workflow_call:    
    inputs:
      buildAll:
        type: boolean
        description: 'Whether or not we should build all BEAMPROJS instead of just the ones with changes.'
        required: true
        default: false

permissions:
  contents: write

jobs:  
  changes:
    runs-on: [self-hosted, Windows]
    
    # This job only runs if we are looking for changes    
    if: ${{ !inputs.buildAll }}
    
    # Expose the list of changed "BEAMPROJ_XXXXX" that were found (this maps to the filter names)
    outputs:            
      BEAMPROJS: ${{ steps.filter.outputs.changes }}
      
    # Clone the repo and find the changed "BEAMPROJ_XXXXX"
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # The filters here are BEAMPROJ-specific. 
          # We should only rebuild artifacts for a specific BEAMPROJ if there are changes to files it considers relevant. 
          filters: |
            BEAMPROJ_HathoraDemo:            
              - 'Plugins/BEAMPROJ_HathoraDemo/**'
              - 'Plugins/BeamableCore/**'
              - 'Plugins/OnlineSubsystemBeamable/**'
              - 'DockerfileWindows'
              - '**.sh'
              - '**.ps1'              
              - 'Source/**'
              - '*.uproject'            
            BEAMPROJ_SteamDemo:            
              - 'Plugins/BEAMPROJ_SteamDemo/**'
              - 'Plugins/BeamableCore/**'
              - 'DockerfileWindows'
              - '**.sh'
              - '**.ps1'
              - 'Source/**'
              - '*.uproject'
            BEAMPROJ_LiveOpsDemo:            
              - 'Plugins/BEAMPROJ_LiveOpsDemo/**'
              - 'Plugins/BeamableCore/**'
              - 'DockerfileWindows'
              - '**.sh'
              - '**.ps1'
              - 'Source/**'
              - '*.uproject'
            BEAMPROJ_DiscordDemo:            
              - 'Plugins/BEAMPROJ_DiscordDemo/**'
              - 'Plugins/BeamableCore/**'
              - 'DockerfileWindows'
              - '**.sh'
              - '**.ps1'
              - 'Source/**'
              - '*.uproject'
            
  build:
    uses: ./.github/workflows/build_windows.yml
    strategy:
      max-parallel: 2
      matrix:
        # The list of BeamProj is defined by "wherever we detected changes" when inputs.buildAll is false
        # The list of BeamProj is a hard-coded list of all BeamProjs when inputs.buildAll is true
        # This is because our RC job also reuses this but needs to generate ALL builds independent of changes. 
        beamProj: ${{ !inputs.buildAll && fromJSON(needs.changes.outputs.BEAMPROJS) || fromJSON(vars.ALL_BEAMPROJS) }}
    with:
      beamProj: ${{ matrix.beamProj }}
      buildType: client