name: Linux Server Build - Hathora Demo

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    paths:
      - 'Dockerfile'
      - '**.sh'
      - 'Source/**'      
      - 'Plugins/BEAMPROJ_HathoraDemo/**'
      - 'Plugins/BeamableCore/**'
      - 'Plugins/OnlineSubsystemBeamable/**'

permissions:
  contents: write

jobs:
  deploy:
    uses: Beamable/UnrealSDK/.github/workflows/build_linux.yml@dev
    strategy:
      max-parallel: 1
      matrix:
        beamProj: ["BEAMPROJ_HathoraDemo"]
        serverBuild: [ true, false ]
    with:
      beamProj: ${{ matrix.beamProj }}
      isServerBuild: ${{ matrix.serverBuild }}
    secrets:
      GHCR_ACTOR: ${{ secrets.GHCR_ACTOR }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}