name: Run UAT

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: beamable/UnrealSDK
        ref: main
    - name: Run UAT
      run: powershell C:\UE_5.1\Engine\Build\BatchFiles\RunUAT.bat BuildCookRun -project=C:/Git/UnrealSDK/BeamableUnreal.uproject -noP4 -clientconfig=Development -serverconfig=Development -nocompile -nocompileeditor -installed -unrealexe="C:\UE_5.1\Engine\Binaries\Win64\UnrealEditor-Cmd.exe" -utf8output -platform=Win64 -build -cook -map=DefaultMap+DefaultMap -CookCultures=en -unversionedcookedcontent -encryptinifiles -ddc=InstalledDerivedDataBackendGraph -pak -makebinaryconfig -manifests -compressed -stage -deploy -cmdline="DefaultMap -Messaging" -device=Windows@DESKTOP-54B40OJ -addcmdline="-SessionId=93429DA948590375D210BE95D3417B52 -SessionOwner='Pedro' -SessionName='Windows'  "
