name: Linux Server Build - Hathora Demo

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    paths:
      - '.github/**HathoraDemo.yml'
      - 'Source/**'
      - 'Plugins/BEAMPROJ_HathoraDemo/**'
      - 'Plugins/BeamableCore/**'
      - 'Plugins/OnlineSubsystemBeamable/**'

permissions:
  contents: write

jobs:
  deploy:
    uses: Beamable/UnrealSDK/.github/workflows/build_linux_server.yml@dev
    with:
      beamProj: BEAMPROJ_HathoraDemo
    secrets:
      GHCR_ACTOR: ${{ secrets.GHCR_ACTOR }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}      