name: Linux Server Build - Hathora Demo

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    paths:
      - 'Plugins/BEAMPROJ_HathoraDemo/**'

permissions:
  contents: write

jobs:
  deploy:
    uses: Beamable/UnrealSDK/.github/workflows/build_linux_server.yml@dev
    with:
      beamProj: BEAMPROJ_HathoraDemo