name: Windows Client Build - Hathora Demo

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
    paths:
      - 'DockerfileWindows'
      - '**.sh'
      - '**.ps1'
      - 'Source/**'
      - 'Plugins/BEAMPROJ_HathoraDemo/**'
      - 'Plugins/BeamableCore/**'
      - 'Plugins/OnlineSubsystemBeamable/**'

permissions:
  contents: write

jobs:
  deploy:
    uses: Beamable/UnrealSDK/.github/workflows/build_windows_client.yml@dev
    strategy:
      max-parallel: 1
      matrix:
        beamProj:
          - BEAMPROJ_HathoraDemo
          - BEAMPROJ_SteamDemo
    with:
      beamProj: ${{ matrix.beamProj }}