name: Windows Client Build - Template

on:
  workflow_call:
    inputs:
      beamProj:
        description: 'The BEAMPROJ we are building. Ie: BEAMPROJ_Sandbox or BEAMPROJ_HathoraDemo.'
        required: true
        default: 'BEAMPROJ_Sandbox'
        type: string

permissions:
  contents: write

jobs:
  deploy:
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: git clean -fdx
      - name: Prepare Repository for Compilation
        run: bash init_repo.sh
      - name: Set BeamProjOverride.txt
        run: |
          echo ${{ inputs.beamProj }} > BeamProjOverride.txt |
          cat BeamProjOverride.txt
      - name: Build image
        run: .\windows_build_project.ps1
      - name: Compress Directory
        run: powershell Compress-Archive PackagedProject artifacts.zip
      - name: Upload Compressed Folder as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts.zip