name: Client build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - testBuild

permissions:
  contents: write

jobs:
  deploy:
    runs-on: unreal-builder
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Pull base image
        run: bash docker_build.sh
      - name: Compress Directory
        run: zip -r artifacts.zip PackagedProject
      - name: Upload Compressed Folder as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.zip