name: Client build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - testBuild

permissions:
  contents: write

jobs:
  deploy:
    runs-on: unreal-builder
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Pull base image
        run: docker pull ghcr.io/epicgames/unreal-engine:dev-5.3.2
      - name: Build the Docker image
        run: docker build .  --progress plain --tag beamable-unreal-client:$(date +%s)
