name: Build - Windows - Client - Dev

on:
  push:
    branches:
      - dev
      - newApproachCi

permissions:
  contents: write

jobs:
    build:
      runs-on: [self-hosted, Windows]
      steps:
        # Run commands to print out more information about the runner
        - name: Print out Additional Runner info 
          run: |
            curl https://api.ipify.org
          
        # Gets the Unreal Repo and the CLI repo
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            lfs: true
            path: BeamableUnreal/
  
        - uses: actions/checkout@v4
          with:
            repository: beamable/BeamableProduct
            fetch-depth: 0
            lfs: true
            path: BeamableProduct/
            ref: main
        - uses: actions/cache@v4
          continue-on-error: false
          with:
            path: |
              BeamableUnreal/Intermediate/
              BeamableUnreal/Saved/
              BeamableUnreal/UnrealSDK.sln
            key: ${{ runner.os }}-${{ hashFiles('/BeamableUnreal/Source/**') }}
            restore-keys: ${{ runner.os }}-
        # Installs .NET 8 so we can run init_repo.sh
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.x            
        # Run Set-Packages for Unreal
        - name: Run Set Packages for local build of the CLI
          working-directory: ./BeamableProduct
          run: bash set-packages.sh "${{ github.workspace }}/BeamableUnreal/" "UNREAL_NugetSource" "" "" "${{ github.workspace }}/BeamableUnreal/Microservices"

        - name: Prepare Repository for compilation v1 
          working-directory: ./BeamableUnreal
          run: bash beam_init_game_maker.sh

        # Run init_repo.sh (needed to setup the project correctly locally)     
        - name: Prepare Repository for compilation v2
          working-directory: ./BeamableUnreal
          run: bash init_repo.sh

        - name: Build files
          working-directory: ./BeamableUnreal
          run: .\windows_build.ps1
