name: Build - Windows - Client - Dev

on:
  push:
    branches:
      - dev
      - newApproachCi

permissions:
  contents: write

jobs:
    build:
      runs-on: windows-latest
      steps:
        # Run commands to print out more information about the runner
        - name: Print out Additional Runner info 
          run: |
            curl https://api.ipify.org
          
        # Gets the Unreal Repo and the CLI repo
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            lfs: true
            path: BeamableUnreal/      
  
        - uses: actions/checkout@v4
          with:
            repository: beamable/BeamableProduct
            fetch-depth: 0
            lfs: true
            path: BeamableProduct/
            ref: main
        - uses: actions/cache@v4
          continue-on-error: false
          with:
            path: |
              BeamableUnreal/Intermediate/
              BeamableUnreal/Saved/
              BeamableUnreal/UnrealSDK.sln
            key: ${{ runner.os }}-${{ hashFiles('/BeamableUnreal/Source/**') }}
            restore-keys: ${{ runner.os }}-
        # Installs .NET 8 so we can run init_repo.sh
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.x            
        # Run Set-Packages for Unreal
        - name: Run Set Packages for local build of the CLI
          working-directory: ./BeamableProduct
          run: bash set-packages.sh "${{ github.workspace }}/BeamableUnreal/" "UNREAL_NugetSource" "" "" "${{ github.workspace }}/BeamableUnreal/Microservices"
        
        # Run init_repo.sh (needed to setup the project correctly locally)     
        - name: Prepare Repository for compilation
          working-directory: ./BeamableUnreal
          run: bash init_repo.sh
        - name: Map Azure File Share
          run: |
            net use Z: \\magazyns.file.core.windows.net\unreal /user:magazyns ${{ secrets.AZURE_STORAGE_KEY }}
        - name: Install Visual Studio Build Tools
          run: choco install visualstudio2022buildtools --package-parameters "--wait --quiet --addProductLang En-us --config ${{ github.workspace }}\BeamableUnreal\.vsconfig"
        - name: Setup MSVC v143 14.34 build tools
          uses: ilammy/msvc-dev-cmd@v1
        - name: Build with Unreal
          uses: OrchidIsle/UE5-Build-Project@0.2.2
          with:
            RUNUAT_PATH: 'Z:/UE_5.4/Engine/Build/BatchFiles/RunUAT.bat'
            UPROJECT_PATH: ${{ github.workspace }}/BeamableUnreal/BeamableUnreal.uproject
            BUILD_CONFIG: Development
            PLATFORM: Win64
            COOK: true
            STAGE: false
            ARCHIVE: true
            ARCHIVE_PATH: ${{ github.workspace }}/ARCHIVED
